var nodemailer = 
require("../../node_modules/nodemailer/lib/nodemailer.js");
var smtpTransport = nodemailer.createTransport("SMTP",{
	service:"Gmail",
	auth:{
		user:process.argv[2]
		,pass:process.argv[3]
	}
});
var message = {
	from:process.argv[2]
	,to:"tcesubmit@gmail.com"
	,subject: "CorePure64: " + process.argv[4] + " extension submission"
	,text:"Hi Tinycore,\n\nThis is an autogenerated email with attachment for the latest build of "+process.argv[4]+" extension.\nThis extension is for the CorePure64 port of tinycore\n"
	,attachments:[{
		filename:process.argv[4]+".tar.gz.bfe"
		,filePath:__dirname+"/release/"+process.argv[4]+".tar.gz.bfe"
		,cid:'attach1'
	}]
}
console.log(message);
smtpTransport.sendMail(message, function(error) {
	if (error) {
		console.log("error sending email:"+error.message);
		return;
	}
	console.log("message sent");
	smtpTransport.close();
});

